Merge Daniels latest changes
QuaCaTeam/quaca pull request #74
Opened 2022-08-13 16:24 UTC by chegerland

- adds Daniel as author
- removes link to old HU git repo
- removes `docsify-ignore-all`
- improves tutorial and documentation

2022-08-15 10:14 UTC, ddanzer requested changes
Tutorial 3 needs to be updated: Currently, no cpp file is created which prevents proper execution of the tutorial's result.

2022-08-30 12:32 UTC, SiMaHer approved these changes

2022-08-30 13:42 UTC, SiMaHer approved these changes

2022-11-07 11:56 UTC, ddanzer approved these changes
Approve.

2022-11-07 12:00 UTC, merged